#!/usr/bin/env lua

local currentDir = debug.getinfo(1).source:match("@?(.*/)")
package.path = package.path .. ";" .. currentDir .. "?.lua"

local utils = require("utils")
local verbose = false
local category = 'None'
local homeDir = os.getenv("HOME")
local filePath = homeDir .. "/.todos/todos.csv"

function addItem(item)
    local file, error = io.open(filePath, "a")

    if error then
        print("ERROR:", error)
        return
    end

    local itemID = tostring(os.time())
    local itemToAdd = string.format("%s,%s,%s\n", itemID, item, category)
    file:write(itemToAdd)
    file:close()

    if verbose then
        print("Todo Category:" .. category)
    end

    print("Todo Added Successfully!")
end

function removeItem(deleteId)
    local file, error = io.open(filePath, "r")

    if error then
        print("ERROR:", error)
        return
    end

    local lines = file:lines()
    local linesTable = {}

    for line in lines do
        local lineSplitTable = utils.split(line, ",")
        local itemId, _, _ = table.unpack(lineSplitTable)
        if itemId ~= deleteId then
            table.insert(linesTable, line)
        end
    end
    file:close()

    file, error = io.open(filePath, "w")

    if error then
        print("ERROR:", error)
        return
    end

    for _, line in ipairs(linesTable) do
        local itemToAdd = string.format("%s\n", line)
        file:write(itemToAdd)
    end
    file:close()
    print("Todo Removed Successfully")

end

function showByCategory(fileLines)
    for line in fileLines do
        local itemId, item, itemCategory = table.unpack(utils.split(line, ","))

        if itemCategory == category then
            if verbose then
                print(string.format("- ID:%s\t Item:%s\t Category:%s", itemId, item, itemCategory))
            else
                print("- " .. item)
            end
        end

    end
end

function showAll(fileLines)
    for line in fileLines do
        local itemId, item, itemCategory = table.unpack(utils.split(line, ","))

        if verbose then
            print(string.format("- ID:%s\t Item:%s\t Category:%s", itemId, item, itemCategory))
        else
            print("- " .. item)
        end

    end
end
function showItems()
    local file, error = io.open(filePath, "r")

    if not file then
        print("No Todo Items")
        if error and verbose then
            print("ERROR:", error)
        end
        return
    end

    local lines = file:lines()

    if category == 'None' then
        showAll(lines)
    else
        showByCategory(lines)
    end

    file:close()

end

function main()
    local command = arg[1]
    local item = arg[2]

    for _, value in ipairs(arg) do
        if value == '--verbose' then
            verbose = true
        end
        local pattern = "^%-%-category=.+"
        if string.match(value, pattern) then
            category = string.sub(value, #'--category=' + 1)
        end
    end

    result = os.execute("mkdir -p " .. homeDir .. "/.todos")

    if verbose then
        if result == true then
            print("Directory created or already exists: " .. homeDir .. "/.todos")
        else
            print("Error creating directory: " .. homeDir .. "/.todos")
        end
    end

    if command == "add" then
        addItem(item)
    elseif command == "remove" then
        removeItem(item)
    elseif command == "show" then
        showItems()
    else
        print("Invalid command. Use 'add', 'remove', or 'show'.")
    end
end

main()
